[colors.bright]
black = "#555753"
blue = "#729FCF"
cyan = "#34E2E2"
green = "#8AE234"
magenta = "#AD7FA8"
red = "#EF2929"
white = "#EEEEEC"
yellow = "#FCE94F"

[colors.cursor]
cursor = "#c5c8c6"

[colors.normal]
black = "#2E3436"
blue = "#3465A4"
cyan = "#06989A"
green = "#8AE234"
magenta = "#75507B"
red = "#CC0000"
white = "#D3D7CF"
yellow = "#C4A000"

[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 16.0

[font.bold]
family = "monospace"
style = "Bold"

[font.normal]
family = "fira code"

[shell]
program = "/bin/fish"

[window]
opacity = 0.7
